level_1 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXXXXXX          XXXXX",
            "X  XXXXXXX  XXXXXX  XXXXX",
            "X       XX  XXXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX        XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXXXXXXXXXX",
            "X         XXXXXXXXXXXXXXX",
            "X                XXXXXXXX",
            "XXXXXXXXXXXX     XXXXX  X",
            "XXXXXXXXX        XXXXX  X",
            "XXX  XXXX               X",
            "XXX                     X",
            "XX          E   XXXXXXXXX",
            "XXXXXXXXXX      XXXXXXXXX",
            "XXXXXXXXXX              X",
            "XX   XXXXX              X",
            "XX   XXXXXXXXXXXXX  XXXXX",
            "XX    XXXXXXXXXXXX  XXXXX",
            "XX           XXXX       X",
            "XXXE                   TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]


level_2 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP        X         X T X",
    "X  XXXXXX X  XXXXX  X   X",
    "X  X  T X X  X T    X   X",
    "X  X XX X X  XXXXX  X  XX",
    "X  X XX X X  X    E     X",
    "X  X XX X X  X  XXX  XXXX",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X    X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX X X  X  X X  X  X",
    "X  X XX   X  X  X X  X  X",
    "X  X E  X X  X  E  T X  X",
    "X  X    X X  X  XX      X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
]


blank_maze = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]